### ISSUE TITLE
Heartbeat event?

### ISSUE THREAD

**Issue by nuance1979** [sysid/sse-starlette#51]
I have a FastAPI server with sse-starlette for SSE. Everything works smoothly except occasionally, my client would receive an event with data looking like a timestamp:

```
data= 2023-04-07 23:36:05.744043
data= 2023-04-07 23:36:20.893051
```

I checked my server code and can be 100% sure that my server never sent events with these data. What could be the reason? How can I filter/ignore them?

**Comment by paxcodes** [comment]
Can you give a minimum, reproducible example? I can try to help.

___

Pax Williams | GitHub <https://github.com/paxcodes> | Portfolio <https://margret.pw> | LinkedIn <https://www.linkedin.com/in/pax-w/>



7 Apr 2023, 16:48 by ***@***.***:

**Comment by nuance1979** [comment]
Thanks @paxcodes ! I believe I found what you were referring to:

https://github.com/sysid/sse-starlette/blob/30ef55c08a8b1512b625752be136a1ea67df6030/sse_starlette/sse.py#L275

However, what's strange is that I've already filtering on `event.type`:

```javascript
async start(controller) {
        const onParse = (event: ParsedEvent | ReconnectInterval) => {
          if (event.type === 'event') {
            const data = event.data;

```

But I still got the ping event. What do you think might be happening here?

**Comment by paxcodes** [comment]
Do I understand your situation correctly?

```js
// client code 

if (event.type === 'event') {
    const data = event.data;
    // !!! data is some sort of timestamp
}
```

If that is the case, that is strange. How are the events parsed on the client side? Who is providing that `event` parameter / ParsedEvent object? An idea is that the code is not parsing the event-stream correctly and setting an incorrect event type.

That assumes that sse-startlette has the expected event-stream text that looks like `\r\nevent: ping\r\n`

So yes, I would check:

a) What your server is actually sending
b) How your client is parsing what it receives from the server

Using a browser as a client might help you troubleshoot as well because you can have visibility to what the server is sending  through the Network tab,

![image](https://user-images.githubusercontent.com/13646646/230736518-ed89a5f7-90f4-4155-b2f0-267c0716e1c0.png)

**Comment by michaelroyzen** [comment]
I'm getting the same issue. Can there be an option for just disabling the heartbeat? That would seem logical to me. It's incredibly annoying (and bad design) to always have to parse it out on the client.

**Comment by paxcodes** [comment]
I'll work on a PR to set the ping as a `comment` instead so clients don't have to deal with it.

**Comment by sysid** [comment]
@paxcodes , thank you again for taking initiative!!

I updated the example `comment_as_ping.py` to show that it is already possible to send the `ping` event as comment. Hope this helps.

**Comment by paxcodes** [comment]
@sysid Would you merge a PR that sends pings as comments? Given the 3 users who commented about them already, I wonder if it's worth doing so that clients don't have to deal with ping events out-of-the-box.
